function(configure_debug target)
	target_compile_definitions(${target} PUBLIC -DELD_DEBUG=1)
	if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
		target_compile_options(${target} PUBLIC /Zi)
	else()
		target_compile_options(${target} PUBLIC -g -Og)
	endif()
endfunction()

function(configure_release target)
	target_compile_definitions(${target} PUBLIC -DELD_DEBUG=0)
	target_compile_options(${target} PRIVATE -O3)
endfunction()

function(configure_win32 target)
	message(WARNING "Detected Windows operating system. Support for this platform is incomplete.")
	target_compile_definitions(${target} PUBLIC -DELD_LINUX=0 -DELD_WIN=1)
	target_link_libraries(${target} PUBLIC OpenGL32 gdiplus)
endfunction()

function(configure_linux target)
	message(WARNING "Detected a linux-y operating system. Support for this platform is incomplete.")
	target_compile_definitions(${target} PUBLIC -DELD_LINUX=1 -DELD_WIN=0)
endfunction()
